swagger: "2.0"
info:
  title: PII Redactor API
  version: "1.0.0"
host: pii-redactor-api-dot-pii-redactor-reetamkole.appspot.com
schemes:
  - https
paths:
  "/**":
    get:
      operationId: proxy_get
      x-google-backend:
        address: http://34.14.191.69
    post:
      operationId: proxy_post
      x-google-backend:
        address: http://34.14.191.69
