apiVersion: apps/v1
kind: Deployment
metadata:
  name: pii-redactor
  namespace: pii-redactor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pii-redactor
  template:
    metadata:
      labels:
        app: pii-redactor
    spec:

      containers:
      - name: esp
        image: gcr.io/endpoints-release/endpoints-runtime:2
        args:
        - "--http_port=8081"
        - "--backend=127.0.0.1:8080"
      
        - "--service=pii-redactor-api.endpoints.pii-redactor-reetamkole.cloud.goog"
        - "--rollout_strategy=managed"
       
        
        ports:
        - containerPort: 8081
        env:
        - name: ESP_PROJECT_ID
          value: "pii-redactor-reetamkole"
      - name: pii-redactor
        image: gcr.io/pii-redactor-reetamkole/pii-redactor:latest
        ports:
        - containerPort: 8080
        env:
        - name: GCS_RAW_BUCKET
          value: "pii-raw-reetamk"
        - name: GCS_PROCESSED_BUCKET
          value: "pii-processed-reetamk"
        - name: GCP_PROJECT_ID
          value: "pii-redactor-reetamkole"
      
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: database-secret
              key: url
        resources:
          requests:
            memory: "256Mi"
            cpu: "125m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5