apiVersion: v1
kind: Service
metadata:
  name: pii-redactor-service
  namespace: pii-redactor
spec:
  selector:
    app: pii-redactor
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  type: LoadBalancer