apiVersion: v1
kind: Service
metadata:
  name: pii-redactor-service
  namespace: pii-redactor
spec:
  selector:
    app: pii-redactor
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081  # Point to ESP port (8081) instead of app port (8080)
  type: LoadBalancer